security:
  oauth2:
    client:
      client-id: clientId
      client-secret: secret
      grant-type: client_credentials
      scope: read
      access-token-uri: http://localhost:9001/oauth/token

# Custom configuration that allows to have multiple OAuth2RestTemplate beans
app:
  oauth2:
    serviceId:
      client-id: clientId
      client-secret: secret
      grant-type: client_credentials
      scope: read
      access-token-uri: http://localhost:9001/oauth/token